application: webscreenshotter
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /content
  static_dir: content

- url: /scripts
  static_dir: scripts

# TODO only for debug
- url: /tools/.*
  script: tools.package.app

- url: /services/.*
  script: services.package.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: django
  version: "1.4"
- name: PIL
  version: "1.1.7"
