application: webscreenshotter
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /content
  static_dir: content

- url: /sripts
  static_dir: sripts

# TODO only for debug
- url: /tools/.*
  script: tools.package.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
